project_id = "ptwrrcqttnvcvlnxsvut"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.create-vendedor]
verify_jwt = true

[functions.create-supervisor]
verify_jwt = true

[functions.manage-vendedor]
verify_jwt = true

[functions.reset-users]
verify_jwt = true

[functions.manage-vendedor-assignment]
verify_jwt = true

